export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const ADD_TO_CART_PRODUCT = "ADD_TO_CART_PRODUCT";
export const REMOVE_ITEM_CART_PRODUCT = "REMOVE_ITEM_CART_PRODUCT";
